Disable test_custom_allreduce (#108)
This PR disables the `test_custom_allreduce` as custom_allreduce has not
been ported over to HIP and is not supported by ROCm Flashinfer.

Currently the `test_custom_allreduce` is a part of Flashinfer ROCm's
test suite and is run on CI. However, since `custom_allreduce` was not
ported over, this causes the test to fail. This is also causing
codecoverage to crash - See pipeline log
[here](https://build.aifoundry.amd.com/job/flashinfer/job/amd-integration-code-coverage/job/post-merge-checkpoint-flashinfer-rocm6.4.x-ubuntu24.04-python3.12-pytorch2.7-test/17/console)

Upon running the test suite locally, the following errors were
encountered:

```
In file included from /root/rm_flashinfer/flashinfer/flashinfer/csrc/custom_all_reduce.cu:3:
/root/micromamba/envs/fi_base/lib/python3.12/site-packages/torch/include/ATen/cuda/Exceptions.h:3:10: fatal error: 'cublas_v2.h' file not found
    3 | #include <cublas_v2.h>
      |          ^~~~~~~~~~~~~
1 error generated when compiling for gfx942.
```

```
/root/rm_flashinfer/flashinfer/flashinfer/csrc/flashinfer_comm_ops.cu:18:10: fatal error: 'flashinfer/distributed/comm_ops.h' file not found
   18 | #include "flashinfer/distributed/comm_ops.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx942.
```

Final Summary

```
=========================== short test summary info ============================
FAILED tests/test_custom_allreduce.py::TestCustomAllReduce::test_correctness
ERROR tests/test_custom_allreduce.py::TestCustomAllReduce::test_correctness
= 1 failed, 23814 passed, 705 skipped, 1 warning, 1 error in 718.89s (0:11:58) =
```

After disabling the test:

```
========== 23814 passed, 705 skipped, 1 warning in 681.99s (0:11:21) ===========
```