[Feature] Support environments built by TheRock build system (#172)
<!-- .github/pull_request_template.md -->

## 📌 Description

This PR introduces ROCm/HIP compatibility improvements:
- Refactor `hip_utils.py` for supporting environments built by TheRock
build system
- Other minor fixes

OBS!
- Requires `export PYTORCH_AMDCLANG=<path-to-amdclang++>`.
- Depends on https://github.com/ROCm/flashinfer/pull/180.

## 🧪 Tests

Currently failing tests:

```
=========================== short test summary info ============================
FAILED tests/test_logits_processor_hip.py::TestLogitsPipeCompilationHIP::test_probs_sample_freq[0.0-normal_distribution(std=1)-32000] - AssertionError: Compiled similarity: tensor([0.9719], device='cuda:0')
assert tensor([0.9719], device='cuda:0') > 0.99
FAILED tests/test_logits_processor_hip.py::TestLogitsPipeCompilationHIP::test_probs_sample_freq[0.0-normal_distribution(std=1)-128256] - AssertionError: Compiled similarity: tensor([0.9895], device='cuda:0')
assert tensor([0.9895], device='cuda:0') > 0.99
============ 2 failed, 589 passed, 12 skipped in 229.71s (0:03:49) =============

=========================== short test summary info ============================
FAILED tests/test_sampling_hip.py::test_sampling_freq[0.0-normal_distribution(std=1)-32000] - AssertionError: similarity: tensor([0.9725], device='cuda:0')
assert tensor([0.9725], device='cuda:0') > 0.99
FAILED tests/test_sampling_hip.py::test_sampling_freq[0.0-normal_distribution(std=1)-128256] - AssertionError: similarity: tensor([0.9894], device='cuda:0')
assert tensor([0.9894], device='cuda:0') > 0.99
============ 2 failed, 772 passed, 18 skipped in 283.44s (0:04:43) =============
```

Above similarity scores fall just below the 0.99 threshold (< 2%
deviation).

Test environment:

```
OS: Ubuntu 22.04.5 LTS (x86_64)
GPU: AMD Instinct MI300X (gfx942:sramecc+:xnack-)
Python version: 3.11.10

rocm                            7.12.0a20260211
rocm-sdk-core                   7.12.0a20260211
rocm-sdk-libraries-gfx94X-dcgpu 7.12.0a20260211

HIP runtime version: 7.3.53390
ROCM used to build PyTorch: 7.3.53390

[pip3] numpy==2.3.1
[pip3] torch==2.10.0+rocm7.12.0a20260211
[pip3] torchao==0.16.0+git3c1065ca6
[pip3] torchaudio==2.10.0+rocm7.12.0a20260211
[pip3] torchcodec==0.10.0
[pip3] torchvision==0.25.0+rocm7.12.0a20260211
[pip3] triton==3.6.0+rocm7.12.0a20260211
[pip3] amd-aiter==0.1.10.post4.dev13+g439606621
```

---------

Co-authored-by: Diptorup Deb <diptorup.deb@amd.com>